### ISSUE TITLE
Request for Clarification on the Use of `pc_path` in `run_blender_splatfields.sh`

### ISSUE THREAD

**Issue by hyeon9698** [markomih/SplatFields#2]
Your work on this project has been truly impressive, and I appreciate the effort that has gone into it.

While reviewing the `run_blender_splatfields.sh` script, I noticed that the process involves reproducing 3DGS first, and subsequently using the point cloud value from iteration 40,000 of the 3DGS as the `pc_path` when reproducing SplatFields3D.

```

# to reproduce 3DGS
python3 train.py -s ${DATASET_ROOT}/${SCENE} --white_background --eval  -m ./output_rep/Blender/$SCENE/${N_VIEWS}views/3DGS --is_static --n_views $N_VIEWS --iterations 40000 --pts_samples hull --max_num_pts 300000 --load_time_step 0 --composition_rank 0
python3 render.py -s ${DATASET_ROOT}/${SCENE} --white_background --eval  -m ./output_rep/Blender/$SCENE/${N_VIEWS}views/3DGS --is_static --n_views $N_VIEWS --iterations 40000 --pts_samples hull --max_num_pts 300000 --load_time_step 0 --composition_rank 0

# # to reproduce SplatFields3D
python3 train.py -s ${DATASET_ROOT}/${SCENE} --white_background --eval  -m ./output_rep/Blender/${SCENE}/${N_VIEWS}views/SplatFields --encoder_type VarTriPlaneEncoder --D 4 --lambda_norm 0.01 --test_iterations -1 --W 128 --n_views ${N_VIEWS} --iterations 40000 --pts_samples load --max_num_pts 100000 --pc_path ./output_rep/Blender/${SCENE}/${N_VIEWS}views/3DGS/point_cloud/iteration_40000/point_cloud.ply --load_time_step 0 --composition_rank 0
python3 render.py -s ${DATASET_ROOT}/${SCENE} --white_background --eval  -m ./output_rep/Blender/${SCENE}/${N_VIEWS}views/SplatFields --encoder_type VarTriPlaneEncoder --D 4 --lambda_norm 0.01 --test_iterations -1 --W 128 --n_views ${N_VIEWS} --iterations 40000 --pts_samples load --max_num_pts 100000 --pc_path ./output_rep/Blender/${SCENE}/${N_VIEWS}views/3DGS/point_cloud/iteration_40000/point_cloud.ply --load_time_step 0 --composition_rank 0

```
I would be very grateful if you could kindly clarify the reasoning behind this approach.
Specifically, I am curious if it is appropriate to use the `pc_path` from the trained 3DGS model, or if there might be any concerns or unintended issues with doing so.

Thank you very much for your time and assistance. I look forward to your guidance.

**Comment by markomih** [comment]
Hi @hyeon9698,

Thank you for your interest in our work.

We observed that initializing SplatFields from reasonable SfM points improves reconstruction. However, since it is challenging to run SfM on the synthetic Blender dataset, we instead use 3DGS point clouds as a proxy.

In practice, the method is not overly sensitive, and substituting any reasonable point cloud should work fine. In the run_dtu.sh script, SplatFields runs on the 3DGS point cloud after only 1k steps. Therefore, using an early initialization on the Blender dataset is unlikely to significantly impact final performance.

Best regards,
Marko
